base_url = "https://alexjj.pages.dev"
theme = "anemone"
compile_sass = false
build_search_index = true
minify_html = true
generate_feeds = true
generate_sitemap = true
taxonomies = [
	{name = "tags", feed = true, paginate_by = 10},
]

title = "Alex Johnstone"
description = "Fond of tea"


[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "Alex"
favicon = "favicon.ico"
list_pages = true
twitter_card = true
enable_search = true
display_author = false

header_nav = [
  { url = "/", name_en = "/home", name_fr = "/accueil/" },
  { url = "/blog", name_en = "/blog", name_fr = "/blog/" },
  { url = "/about", name_en = "/about", name_fr = "/concernant/" },
  { url = "/books", name_en = "/books", name_fr = "/books/" }
]
