base_url = "https://alexjj.com"
theme = "anemone"
compile_sass = false
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]
generate_sitemap = true
taxonomies = [
	{name = "tags", feed = true, paginate_by = 10},
]

title = "alexjj.com"
description = "Fond of tea"
author = "Alex Johnstone"


[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "Alex"
favicon = "favicon.ico"
list_pages = false
twitter_card = true
enable_search = true
display_author = false

header_nav = [
  { url = "/", name_en = "/home" },
  { url = "/blog", name_en = "/blog" },
  { url = "/rss.xml", name_en = "/rss" }
]
